const colors = require('tailwindcss/colors')
const defaultTheme = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      sm: { max: '365px' },
      md: '750px',
    },
    ...colors,
    gray: {
      10: '#FFFFFF',
      20: '#EDEDED',
      30: '#DBDBDB',
      40: '#A6A6A6',
      50: '#555555',
      60: '#444444',
      70: '#222222',
      80: '#000000',
    },
    primary: {
      10: '#D3FF52',
    },
    blue: {
      50: '#3234FB',
    },
    extend: {
      fontSize: {
        '8px': '8px',
        '9px': '9px',
        '10px': '10px',
        '11px': '11px',
        '12px': '12px',
        '13px': '13px',
        '14px': '14px',
        '15px': '15px',
        '16px': '16px',
        '17px': '17px',
        '18px': '18px',
        '19px': '19px',
        '20px': '20px',
        '21px': '21px',
        '22px': '22px',
        '23px': '23px',
        '24px': '24px',
      },
      spacing: {
        '2px': '2px',
        '3px': '3px',
        '4px': '4px',
        '5px': '5px',
        '6px': '6px',
        '7px': '7px',
        '8px': '8px',
        '9px': '9px',
        '10px': '10px',
        '11px': '11px',
        '12px': '12px',
        '13px': '13px',
        '14px': '14px',
        '15px': '15px',
        '16px': '16px',
        '17px': '17px',
        '18px': '18px',
        '19px': '19px',
        '20px': '20px',
        '21px': '21px',
        '22px': '22px',
        '23px': '23px',
        '24px': '24px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
    fontFamily: {
      'gilroy-regular': ['Gilroy-Regular', 'sans-serif'],
      'gilroy-medium': ['Gilroy-Medium', 'sans-serif'],
      'gilroy-bold': ['Gilroy-Bold', 'sans-serif'],
      'gilroy-heavy': ['Gilroy-Heavy', 'sans-serif'],
      'gilroy-light': ['Gilroy-Light', 'sans-serif'],
      suit: ['"SUIT Variable"', 'sans-serif'],
      sans: ['"SUIT Variable"', ...defaultTheme.fontFamily.sans],
    },
  },
  plugins: [require('tailwindcss-animate')],
}
