import './globals.css'
import type { Metadata } from 'next'
import Providers from '@/lib/providers'

export const metadata: Metadata = {
  title: 'Banuddy',
  description: 'Generated by pair3',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="font-display">
      <body suppressHydrationWarning={true}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
