import MainLayout from '@/components/layout/MainLayout'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Banuddy',
  description: 'Generated by pair3',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="font-display">
      <body>
        <MainLayout children={children} />
      </body>
    </html>
  )
}
